(define (problem blocks-01)
  (:domain blocks)
  (:objects A B C D - block)
  (:init (clear A) (clear B) (clear C) (clear D) (ontable A)
         (ontable B) (ontable C) (ontable D) (handempty) (= (moves) 0) )
  (:goal (and (on D C) (on C B) (on B A) ) )
  (:metric minimize (moves))
)